import io
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.graphics.shapes import Drawing, Rect, String, Line, Polygon
from reportlab.graphics import renderPDF
from datetime import datetime

# ── Colour palette ──────────────────────────────────────────────
C_PRIMARY   = colors.HexColor("#4f46e5")   # indigo
C_SECONDARY = colors.HexColor("#0891b2")   # cyan
C_ACCENT    = colors.HexColor("#7c3aed")   # violet
C_SUCCESS   = colors.HexColor("#059669")   # green
C_WARN      = colors.HexColor("#d97706")   # amber
C_DARK      = colors.HexColor("#0f172a")   # slate-900
C_MID       = colors.HexColor("#334155")   # slate-700
C_LIGHT     = colors.HexColor("#64748b")   # slate-500
C_BORDER    = colors.HexColor("#e2e8f0")   # slate-200
C_COVER_BG  = colors.HexColor("#0f172a")
C_WHITE     = colors.white

W = letter[0] - 108   # usable text width (54pt margins each side)


# ── Numbered canvas with header/footer ──────────────────────────
class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_decorations(total)
            super().showPage()
        super().save()

    def _draw_decorations(self, total):
        self.saveState()
        pg = self._pageNumber
        # Skip cover page decorations
        if pg == 1:
            self.restoreState()
            return
        # Header bar
        self.setFillColor(C_PRIMARY)
        self.rect(54, 745, W, 2, fill=1, stroke=0)
        self.setFont("Helvetica", 8)
        self.setFillColor(C_LIGHT)
        self.drawString(54, 753, "LERNIX — Professional Curriculum Report")
        self.drawRightString(54 + W, 753, datetime.now().strftime("%B %d, %Y"))
        # Footer
        self.setFillColor(C_BORDER)
        self.rect(54, 44, W, 1, fill=1, stroke=0)
        self.setFont("Helvetica", 8)
        self.setFillColor(C_LIGHT)
        self.drawString(54, 32, "Generated by LERNIX AI  |  Powered by IBM Granite")
        self.drawRightString(54 + W, 32, f"Page {pg} of {total}")
        self.restoreState()


# ── Style factory ────────────────────────────────────────────────
def _styles():
    base = getSampleStyleSheet()

    def ps(name, **kw):
        p = ParagraphStyle(name, parent=base["Normal"], **kw)
        return p

    return {
        "cover_title": ps("CoverTitle", fontName="Helvetica-Bold",
                          fontSize=32, leading=38, textColor=C_WHITE, spaceAfter=10),
        "cover_sub":   ps("CoverSub", fontName="Helvetica",
                          fontSize=14, leading=18, textColor=colors.HexColor("#94a3b8"), spaceAfter=6),
        "cover_meta":  ps("CoverMeta", fontName="Helvetica",
                          fontSize=11, leading=15, textColor=colors.HexColor("#cbd5e1")),
        "toc_title":   ps("TocTitle", fontName="Helvetica-Bold",
                          fontSize=18, leading=22, textColor=C_PRIMARY, spaceAfter=16),
        "toc_item":    ps("TocItem", fontName="Helvetica",
                          fontSize=11, leading=16, textColor=C_MID, leftIndent=12, spaceAfter=4),
        "toc_sub":     ps("TocSub", fontName="Helvetica",
                          fontSize=9.5, leading=13, textColor=C_LIGHT, leftIndent=28, spaceAfter=3),
        "h1":          ps("H1", fontName="Helvetica-Bold",
                          fontSize=18, leading=22, textColor=C_DARK,
                          spaceBefore=14, spaceAfter=8, keepWithNext=True),
        "h2":          ps("H2", fontName="Helvetica-Bold",
                          fontSize=13, leading=16, textColor=C_PRIMARY,
                          spaceBefore=10, spaceAfter=5, keepWithNext=True),
        "h3":          ps("H3", fontName="Helvetica-Bold",
                          fontSize=11, leading=14, textColor=C_SECONDARY,
                          spaceBefore=8, spaceAfter=4, keepWithNext=True),
        "body":        ps("Body", fontName="Helvetica",
                          fontSize=10, leading=14, textColor=C_MID, spaceAfter=6),
        "bullet":      ps("Bullet", fontName="Helvetica",
                          fontSize=9.5, leading=13, textColor=C_MID,
                          leftIndent=16, firstLineIndent=-10, spaceAfter=3),
        "label":       ps("Label", fontName="Helvetica-Bold",
                          fontSize=10, leading=13, textColor=C_DARK),
        "badge":       ps("Badge", fontName="Helvetica-Bold",
                          fontSize=8, leading=10, textColor=C_WHITE),
        "caption":     ps("Caption", fontName="Helvetica-Oblique",
                          fontSize=8.5, leading=11, textColor=C_LIGHT,
                          spaceAfter=8, alignment=1),
    }


# ── Helpers ──────────────────────────────────────────────────────
def _hr(story):
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_BORDER, spaceAfter=8, spaceBefore=4))


def _section_banner(story, text, s):
    """Full-width indigo banner for section headings."""
    banner_data = [[Paragraph(f"<font color='white'><b>{text}</b></font>", s["h1"])]]
    t = Table(banner_data, colWidths=[W])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), C_PRIMARY),
        ("TOPPADDING",    (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING",   (0, 0), (-1, -1), 14),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 14),
    ]))
    story.append(Spacer(1, 8))
    story.append(t)
    story.append(Spacer(1, 10))


def _info_table(rows, s):
    """Two-column key-value info table."""
    data = [[Paragraph(k, s["label"]), Paragraph(str(v), s["body"])] for k, v in rows]
    t = Table(data, colWidths=[1.8 * inch, W - 1.8 * inch])
    t.setStyle(TableStyle([
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING",    (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LINEBELOW",     (0, 0), (-1, -1), 0.4, C_BORDER),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
    ]))
    return t


def _colored_table(header_row, data_rows, s, col_widths=None):
    """Styled table with indigo header row."""
    header = [Paragraph(f"<font color='white'><b>{h}</b></font>", s["label"]) for h in header_row]
    rows = [[Paragraph(str(c), s["body"]) for c in row] for row in data_rows]
    col_widths = col_widths or [W / len(header_row)] * len(header_row)
    t = Table([header] + rows, colWidths=col_widths)
    t.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), C_PRIMARY),
        ("BACKGROUND",    (0, 1), (-1, -1), colors.HexColor("#f8fafc")),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.white, colors.HexColor("#f1f5f9")]),
        ("GRID",          (0, 0), (-1, -1), 0.4, C_BORDER),
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
    ]))
    return t


# ── Diagrams ─────────────────────────────────────────────────────
def _learning_path_flowchart(semesters):
    """Horizontal flowchart of semesters → courses."""
    box_w, box_h, gap = 90, 28, 18
    total_w = min(len(semesters) * (box_w + gap) + gap, W)
    height = 80
    d = Drawing(total_w, height)
    colors_cycle = [C_PRIMARY, C_SECONDARY, C_ACCENT, C_SUCCESS, C_WARN,
                    colors.HexColor("#db2777"), colors.HexColor("#ea580c")]
    x = gap
    for i, sem in enumerate(semesters):
        col = colors_cycle[i % len(colors_cycle)]
        # Box
        d.add(Rect(x, height - box_h - 10, box_w, box_h,
                   fillColor=col, strokeColor=C_WHITE, strokeWidth=1, rx=4, ry=4))
        # Label
        label = f"Sem {sem['semester_number']}"
        courses_count = f"{len(sem['courses'])} courses"
        d.add(String(x + box_w / 2, height - 22, label,
                     fontName="Helvetica-Bold", fontSize=9,
                     fillColor=C_WHITE, textAnchor="middle"))
        d.add(String(x + box_w / 2, height - 34, courses_count,
                     fontName="Helvetica", fontSize=7.5,
                     fillColor=colors.HexColor("#e0e7ff"), textAnchor="middle"))
        # Arrow to next
        if i < len(semesters) - 1:
            ax = x + box_w + 2
            ay = height - box_h / 2 - 10
            d.add(Line(ax, ay, ax + gap - 4, ay,
                       strokeColor=C_LIGHT, strokeWidth=1.2))
            # Arrowhead
            d.add(Polygon([ax + gap - 4, ay,
                           ax + gap - 10, ay + 4,
                           ax + gap - 10, ay - 4],
                          fillColor=C_LIGHT, strokeColor=C_LIGHT))
        x += box_w + gap
    return d


def _skill_progress_chart(skills_data):
    """Horizontal bar chart for skill levels."""
    bar_h = 14
    gap_y = 8
    label_w = 120
    bar_area = W - label_w - 60
    rows = list(skills_data.items())[:8]
    height = len(rows) * (bar_h + gap_y) + 20
    d = Drawing(W, height)
    y = height - bar_h - 10
    bar_colors = [C_PRIMARY, C_SECONDARY, C_ACCENT, C_SUCCESS,
                  C_WARN, colors.HexColor("#db2777"),
                  colors.HexColor("#ea580c"), colors.HexColor("#0891b2")]
    for i, (skill, level) in enumerate(rows):
        pct = min(max(int(level), 0), 100) / 100
        col = bar_colors[i % len(bar_colors)]
        # Background track
        d.add(Rect(label_w, y, bar_area, bar_h,
                   fillColor=colors.HexColor("#e2e8f0"), strokeColor=None))
        # Fill
        d.add(Rect(label_w, y, bar_area * pct, bar_h,
                   fillColor=col, strokeColor=None, rx=3, ry=3))
        # Label
        d.add(String(label_w - 6, y + 3, skill[:20],
                     fontName="Helvetica", fontSize=8,
                     fillColor=C_MID, textAnchor="end"))
        # Percentage
        d.add(String(label_w + bar_area * pct + 4, y + 3, f"{int(pct*100)}%",
                     fontName="Helvetica-Bold", fontSize=7.5,
                     fillColor=C_MID, textAnchor="start"))
        y -= (bar_h + gap_y)
    return d


def _semester_progress_diagram(semesters):
    """Vertical stacked bar showing credit distribution per semester."""
    bar_w = min(50, (W - 60) / max(len(semesters), 1))
    max_credits = max(
        sum(c.get("credits", 3) for c in s["courses"]) for s in semesters
    ) or 20
    chart_h = 100
    gap = 10
    total_w = len(semesters) * (bar_w + gap) + gap + 40
    d = Drawing(total_w, chart_h + 30)
    x = 40
    for sem in semesters:
        total = sum(c.get("credits", 3) for c in sem["courses"])
        bar_height = int((total / max_credits) * chart_h)
        d.add(Rect(x, 20, bar_w, bar_height,
                   fillColor=C_SECONDARY, strokeColor=C_WHITE,
                   strokeWidth=0.5, rx=3, ry=3))
        d.add(String(x + bar_w / 2, 22 + bar_height, str(total),
                     fontName="Helvetica-Bold", fontSize=8,
                     fillColor=C_DARK, textAnchor="middle"))
        d.add(String(x + bar_w / 2, 8, f"S{sem['semester_number']}",
                     fontName="Helvetica", fontSize=8,
                     fillColor=C_LIGHT, textAnchor="middle"))
        x += bar_w + gap
    # Y-axis label
    d.add(String(6, chart_h / 2 + 10, "Credits",
                 fontName="Helvetica-Oblique", fontSize=7.5,
                 fillColor=C_LIGHT, textAnchor="middle"))
    return d


# ── Cover page ───────────────────────────────────────────────────
def _build_cover(story, topic, curriculum_data, s):
    # Full dark background via table trick
    cover_data = [[""]]
    cover_bg = Table(cover_data, colWidths=[W], rowHeights=[letter[1] - 144])
    cover_bg.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), C_COVER_BG),
    ]))
    story.append(cover_bg)

    # Overlay content via another table on top (we build inside the page frame)
    # Use spacers + styled paragraphs after the background
    story.append(Spacer(1, -letter[1] + 180))  # pull back up

    # Accent top stripe
    stripe = Table([[""]], colWidths=[W], rowHeights=[6])
    stripe.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, -1), C_PRIMARY)]))
    story.append(stripe)
    story.append(Spacer(1, 36))

    lernix_label = Paragraph(
        "<font color='#94a3b8' size='11'>LERNIX AI  ·  Professional Curriculum Report</font>", s["cover_sub"]
    )
    story.append(lernix_label)
    story.append(Spacer(1, 20))

    story.append(Paragraph(topic, s["cover_title"]))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        f"<font color='#94a3b8'>Field of Study: {curriculum_data.get('field_of_study','—')}</font>",
        s["cover_sub"]
    ))
    story.append(Spacer(1, 40))

    # Meta grid
    meta_items = [
        ["Duration", f"{curriculum_data.get('duration_semesters','—')} Semesters"],
        ["Total Courses", str(sum(len(sem["courses"]) for sem in curriculum_data.get("semesters", [])))],
        ["Generated By", "LERNIX AI  (IBM Granite)"],
        ["Date", datetime.now().strftime("%B %d, %Y")],
        ["Paradigm", "Outcome-Based Education (OBE)"],
        ["Standard", "ACM / IEEE Joint Guidelines"],
    ]
    meta_rows = []
    for label, val in meta_items:
        meta_rows.append([
            Paragraph(f"<font color='#64748b'>{label}</font>", s["cover_meta"]),
            Paragraph(f"<font color='#e2e8f0'><b>{val}</b></font>", s["cover_meta"]),
        ])
    meta_t = Table(meta_rows, colWidths=[1.6 * inch, 3.4 * inch])
    meta_t.setStyle(TableStyle([
        ("LINEBELOW",     (0, 0), (-1, -1), 0.4, colors.HexColor("#1e293b")),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING",   (0, 0), (-1, -1), 4),
    ]))
    story.append(meta_t)
    story.append(PageBreak())


# ── Table of Contents ────────────────────────────────────────────
def _build_toc(story, curriculum_data, s):
    story.append(Paragraph("Table of Contents", s["toc_title"]))
    _hr(story)
    sections = [
        ("1", "Program Overview"),
        ("2", "Semester-wise Curriculum"),
    ]
    for sem in curriculum_data.get("semesters", []):
        sections.append(("", f"  Semester {sem['semester_number']} — {len(sem['courses'])} Courses"))
    sections += [
        ("3", "Learning Resources"),
        ("4", "Skills Mapping"),
        ("5", "Career Roadmap"),
        ("6", "Capstone Project Recommendations"),
        ("7", "Visual Analytics"),
    ]
    for num, title in sections:
        prefix = f"<b>{num}.</b>  " if num else "     "
        style = s["toc_item"] if num else s["toc_sub"]
        story.append(Paragraph(f"{prefix}{title}", style))
    story.append(PageBreak())


# ── Section 1: Program Overview ──────────────────────────────────
def _build_overview(story, topic, curriculum_data, report, s):
    _section_banner(story, "1.  Program Overview", s)

    total_courses = sum(len(sem["courses"]) for sem in curriculum_data.get("semesters", []))
    total_credits = sum(
        c.get("credits", 3)
        for sem in curriculum_data.get("semesters", [])
        for c in sem["courses"]
    )
    story.append(_info_table([
        ("Program Title",   topic),
        ("Field of Study",  curriculum_data.get("field_of_study", "—")),
        ("Duration",        f"{curriculum_data.get('duration_semesters','—')} Semesters"),
        ("Total Courses",   str(total_courses)),
        ("Total Credits",   str(total_credits)),
        ("Design Paradigm", "Outcome-Based Education (OBE)"),
        ("Target Audience", report.get("target_audience", "Undergraduate / Professional")),
    ], s))
    story.append(Spacer(1, 12))

    # Learning objectives
    story.append(Paragraph("Program Learning Objectives", s["h2"]))
    for obj in report.get("learning_objectives", [
        f"Develop comprehensive understanding of {topic} principles.",
        "Apply industry-standard tools and frameworks.",
        "Design, implement and evaluate real-world systems.",
        "Prepare graduates for professional and research roles.",
    ]):
        story.append(Paragraph(f"• {obj}", s["bullet"]))

    story.append(Spacer(1, 10))
    story.append(Paragraph("Program Description", s["h2"]))
    story.append(Paragraph(report.get("program_description",
        f"This program provides a structured pathway through {topic}, covering "
        f"both theoretical foundations and practical applications across "
        f"{curriculum_data.get('duration_semesters','multiple')} semesters."
    ), s["body"]))
    story.append(PageBreak())


# ── Section 2: Semester-wise Curriculum ─────────────────────────
def _build_semesters(story, curriculum_data, s):
    _section_banner(story, "2.  Semester-wise Curriculum", s)

    for sem in curriculum_data.get("semesters", []):
        sem_num = sem["semester_number"]
        story.append(Paragraph(f"Semester {sem_num}", s["h2"]))

        # Quick summary table
        summary_header = ["Code", "Course Title", "Credits", "Difficulty", "Relevance"]
        summary_rows = [
            [
                c.get("code", "—"),
                c.get("name", "—"),
                str(c.get("credits", 3)),
                c.get("difficulty", "—"),
                f"{c.get('industry_relevance_score', 90)}%",
            ]
            for c in sem["courses"]
        ]
        story.append(_colored_table(
            summary_header, summary_rows, s,
            col_widths=[0.9*inch, 2.6*inch, 0.7*inch, 1.1*inch, 0.9*inch]
        ))
        story.append(Spacer(1, 10))

        for course in sem["courses"]:
            cs = []
            cs.append(Paragraph(f"{course.get('code','')}: {course.get('name','')}", s["h3"]))
            cs.append(_info_table([
                ("Credits",       str(course.get("credits", 3))),
                ("Difficulty",    course.get("difficulty", "—")),
                ("Weekly Hours",  f"{course.get('weekly_hours', course.get('credits',3)*2)} hrs"),
                ("Relevance",     f"{course.get('industry_relevance_score', 90)}%"),
                ("Prerequisites", ", ".join(course.get("prerequisites", [])) or "None"),
            ], s))
            cs.append(Spacer(1, 4))
            cs.append(Paragraph("<b>Description</b>", s["label"]))
            cs.append(Paragraph(course.get("description", "—"), s["body"]))
            cs.append(Paragraph("<b>Learning Outcomes</b>", s["label"]))
            for lo in course.get("learning_outcomes", []):
                cs.append(Paragraph(f"• {lo}", s["bullet"]))
            careers = ", ".join(course.get("career_opportunities", []))
            if careers:
                cs.append(Paragraph(f"<b>Career Pathways:</b> {careers}", s["body"]))
            projs = ", ".join(course.get("recommended_projects", []))
            if projs:
                cs.append(Paragraph(f"<b>Recommended Capstone:</b> {projs}", s["body"]))
            assessments = ", ".join(course.get("assessment_methods", []))
            if assessments:
                cs.append(Paragraph(f"<b>Assessment Structure:</b> {assessments}", s["body"]))
            cs.append(HRFlowable(width="100%", thickness=0.4, color=C_BORDER,
                                  spaceAfter=6, spaceBefore=6))
            story.append(KeepTogether(cs))

        story.append(PageBreak())


# ── Section 3: Learning Resources ───────────────────────────────
def _build_resources(story, curriculum_data, report, s):
    _section_banner(story, "3.  Learning Resources", s)

    # Global resources from report
    global_res = report.get("learning_resources", {})
    categories = [
        ("📚 Books & Textbooks",           global_res.get("books", [])),
        ("📖 Official Documentation",      global_res.get("documentation", [])),
        ("🎥 Video Courses & MOOCs",        global_res.get("video_courses", [])),
        ("🔬 Research Papers",             global_res.get("research_papers", [])),
        ("🏭 Industry References",         global_res.get("industry_references", [])),
    ]
    for cat_title, items in categories:
        if not items:
            continue
        story.append(Paragraph(cat_title, s["h3"]))
        for item in items:
            if isinstance(item, dict):
                story.append(Paragraph(
                    f"• <b>{item.get('title','')}</b>"
                    f"{' — ' + item.get('author','') if item.get('author') else ''}"
                    f"{' | ' + item.get('url','') if item.get('url') else ''}",
                    s["bullet"]
                ))
            else:
                story.append(Paragraph(f"• {item}", s["bullet"]))
        story.append(Spacer(1, 6))

    # Per-course resource table
    story.append(Paragraph("Course-level Reference Links", s["h2"]))
    header = ["Course", "Resource", "URL"]
    rows = []
    for sem in curriculum_data.get("semesters", []):
        for course in sem["courses"]:
            for res in course.get("resources", []):
                rows.append([
                    course.get("code", ""),
                    res.get("title", ""),
                    res.get("url", ""),
                ])
    if rows:
        story.append(_colored_table(
            header, rows, s,
            col_widths=[0.9*inch, 2.5*inch, 3.4*inch]
        ))
    story.append(PageBreak())


# ── Section 4: Skills Mapping ────────────────────────────────────
def _build_skills(story, report, s):
    _section_banner(story, "4.  Skills Mapping", s)

    skills = report.get("skills_mapping", {})
    categories = [
        ("Technical Skills",       skills.get("technical_skills", [])),
        ("Tools & Platforms",      skills.get("tools", [])),
        ("Frameworks & Libraries", skills.get("frameworks", [])),
        ("Industry Competencies",  skills.get("industry_competencies", [])),
    ]
    for cat, items in categories:
        if not items:
            continue
        story.append(Paragraph(cat, s["h3"]))
        # Render as badge-style row
        badge_data = [Paragraph(f"  {item}  ", s["body"]) for item in items]
        if badge_data:
            cols = min(len(badge_data), 4)
            rows_data = [badge_data[i:i+cols] for i in range(0, len(badge_data), cols)]
            # Pad last row
            while len(rows_data[-1]) < cols:
                rows_data[-1].append(Paragraph("", s["body"]))
            t = Table(rows_data, colWidths=[W / cols] * cols)
            t.setStyle(TableStyle([
                ("BACKGROUND",    (0, 0), (-1, -1), colors.HexColor("#eff6ff")),
                ("GRID",          (0, 0), (-1, -1), 0.5, C_BORDER),
                ("TOPPADDING",    (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("LEFTPADDING",   (0, 0), (-1, -1), 8),
                ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
            ]))
            story.append(t)
            story.append(Spacer(1, 10))

    # Skill progression bar chart
    story.append(Paragraph("Skill Progression Overview", s["h2"]))
    skill_levels = report.get("skill_levels", {})
    if skill_levels:
        d = _skill_progress_chart(skill_levels)
        story.append(d)
        story.append(Paragraph("Skill mastery progression across the program curriculum.", s["caption"]))
    story.append(PageBreak())


# ── Section 5: Career Roadmap ────────────────────────────────────
def _build_career(story, report, s):
    _section_banner(story, "5.  Career Roadmap", s)

    career = report.get("career_roadmap", {})
    levels = [
        ("🟢 Beginner Roles",      career.get("beginner_roles", [])),
        ("🔵 Intermediate Roles",  career.get("intermediate_roles", [])),
        ("🟣 Advanced Roles",      career.get("advanced_roles", [])),
    ]
    for level_title, roles in levels:
        if not roles:
            continue
        story.append(Paragraph(level_title, s["h3"]))
        role_rows = []
        for role in roles:
            if isinstance(role, dict):
                role_rows.append([
                    role.get("title", ""),
                    role.get("description", ""),
                    role.get("salary", "—"),
                ])
            else:
                role_rows.append([str(role), "", "—"])
        if role_rows:
            story.append(_colored_table(
                ["Role", "Description", "Avg. Salary"],
                role_rows, s,
                col_widths=[1.8*inch, 3.4*inch, 1.6*inch]
            ))
        story.append(Spacer(1, 10))

    salary = report.get("salary_insights")
    if salary:
        story.append(Paragraph("Salary Insights", s["h2"]))
        if isinstance(salary, dict):
            story.append(_info_table(list(salary.items()), s))
        else:
            story.append(Paragraph(str(salary), s["body"]))
    story.append(PageBreak())


# ── Section 6: Capstone Recommendations ─────────────────────────
def _build_capstone(story, report, s):
    _section_banner(story, "6.  Capstone Project Recommendations", s)

    projects = report.get("capstone_projects", [])
    for i, proj in enumerate(projects, 1):
        cs = []
        if isinstance(proj, dict):
            cs.append(Paragraph(f"{i}. {proj.get('title','Project')}", s["h3"]))
            cs.append(Paragraph(proj.get("description", ""), s["body"]))
            if proj.get("tech_stack"):
                cs.append(Paragraph(
                    f"<b>Tech Stack:</b> {', '.join(proj['tech_stack'])}", s["body"]
                ))
            if proj.get("deliverables"):
                cs.append(Paragraph("<b>Deliverables:</b>", s["label"]))
                for d in proj["deliverables"]:
                    cs.append(Paragraph(f"• {d}", s["bullet"]))
            if proj.get("difficulty"):
                cs.append(Paragraph(f"<b>Difficulty:</b> {proj['difficulty']}", s["body"]))
        else:
            cs.append(Paragraph(f"{i}. {proj}", s["h3"]))
        cs.append(HRFlowable(width="100%", thickness=0.4, color=C_BORDER,
                              spaceAfter=6, spaceBefore=6))
        story.append(KeepTogether(cs))
    story.append(PageBreak())


# ── Section 7: Visual Analytics ──────────────────────────────────
def _build_visuals(story, curriculum_data, s):
    _section_banner(story, "7.  Visual Analytics", s)
    semesters = curriculum_data.get("semesters", [])
    if not semesters:
        story.append(Paragraph("No semester data available.", s["body"]))
        return

    story.append(Paragraph("Learning Path Flowchart", s["h2"]))
    story.append(Paragraph(
        "Visualisation of the semester-by-semester learning progression.", s["body"]
    ))
    d1 = _learning_path_flowchart(semesters)
    story.append(d1)
    story.append(Paragraph(
        "Figure 1: Semester learning path — each block represents one semester.", s["caption"]
    ))
    story.append(Spacer(1, 16))

    story.append(Paragraph("Semester Credit Distribution", s["h2"]))
    d2 = _semester_progress_diagram(semesters)
    story.append(d2)
    story.append(Paragraph(
        "Figure 2: Total credits per semester — shows workload distribution.", s["caption"]
    ))
    story.append(Spacer(1, 16))

    story.append(Paragraph("Course Dependency Overview", s["h2"]))
    # Dependency table
    dep_rows = []
    for sem in semesters:
        for course in sem["courses"]:
            prereqs = ", ".join(course.get("prerequisites", [])) or "None"
            dep_rows.append([
                f"S{sem['semester_number']}",
                course.get("code", ""),
                course.get("name", ""),
                prereqs,
            ])
    if dep_rows:
        story.append(_colored_table(
            ["Sem", "Code", "Course Title", "Prerequisites"],
            dep_rows, s,
            col_widths=[0.5*inch, 1.0*inch, 2.8*inch, 2.5*inch]
        ))
    story.append(Paragraph(
        "Figure 3: Course prerequisite dependency map.", s["caption"]
    ))


# ── Main entry point ─────────────────────────────────────────────
def generate_curriculum_pdf(curriculum_data):
    """Original function — basic report for existing curriculum exports."""
    return generate_professional_report(
        topic=curriculum_data.get("export_topic", curriculum_data.get("title", "Curriculum")),
        curriculum_data=curriculum_data,
        report={}
    )


def generate_professional_report(topic, curriculum_data, report):
    """
    Full university-grade PDF report.
    `report` is the enriched data dict from llm_service.generate_full_report_data().
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54, rightMargin=54,
        topMargin=72, bottomMargin=72,
        title=topic,
        author="LERNIX AI",
        subject=f"Curriculum Report — {topic}",
    )
    s = _styles()
    story = []

    _build_cover(story, topic, curriculum_data, s)
    _build_toc(story, curriculum_data, s)
    _build_overview(story, topic, curriculum_data, report, s)
    _build_semesters(story, curriculum_data, s)
    _build_resources(story, curriculum_data, report, s)
    _build_skills(story, report, s)
    _build_career(story, report, s)
    _build_capstone(story, report, s)
    _build_visuals(story, curriculum_data, s)

    doc.build(story, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer.getvalue()
