import io
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether, HRFlowable, BaseDocTemplate, Frame, PageTemplate
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.graphics.shapes import Drawing, Rect, String, Line, Polygon
from datetime import datetime

# ── Palette ──────────────────────────────────────────────────────
C_PRIMARY  = colors.HexColor("#4f46e5")
C_CYAN     = colors.HexColor("#0891b2")
C_VIOLET   = colors.HexColor("#7c3aed")
C_GREEN    = colors.HexColor("#059669")
C_AMBER    = colors.HexColor("#d97706")
C_DARK     = colors.HexColor("#0f172a")
C_MID      = colors.HexColor("#334155")
C_MUTED    = colors.HexColor("#64748b")
C_BORDER   = colors.HexColor("#e2e8f0")
C_LIGHT_BG = colors.HexColor("#f8fafc")
C_STRIPE   = colors.HexColor("#f1f5f9")

PW, PH = letter          # 612 x 792 pt
LM = RM = 54             # left/right margin
TM = BM = 72             # top/bottom margin
W  = PW - LM - RM        # usable width = 504 pt


# ── Numbered Canvas ───────────────────────────────────────────────
class _Canvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._pages = []

    def showPage(self):
        self._pages.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        n = len(self._pages)
        for state in self._pages:
            self.__dict__.update(state)
            self._decorate(n)
            super().showPage()
        super().save()

    def _decorate(self, total):
        pg = self._pageNumber
        self.saveState()
        if pg == 1:                          # cover — no header/footer
            self.restoreState()
            return
        # header rule
        self.setFillColor(C_PRIMARY)
        self.rect(LM, PH - TM + 10, W, 2, fill=1, stroke=0)
        self.setFont("Helvetica", 7.5)
        self.setFillColor(C_MUTED)
        self.drawString(LM, PH - TM + 14, "LERNIX — Professional Curriculum Report")
        self.drawRightString(LM + W, PH - TM + 14,
                             datetime.now().strftime("%B %d, %Y"))
        # footer rule
        self.setFillColor(C_BORDER)
        self.rect(LM, BM - 14, W, 0.5, fill=1, stroke=0)
        self.setFont("Helvetica", 7.5)
        self.setFillColor(C_MUTED)
        self.drawString(LM, BM - 24,
                        "Generated by LERNIX AI  |  IBM Granite  |  ACM/IEEE Standards")
        self.drawRightString(LM + W, BM - 24, f"Page {pg} of {total}")
        self.restoreState()


# ── Style factory ─────────────────────────────────────────────────
def _S():
    b = getSampleStyleSheet()
    def p(name, **kw):
        return ParagraphStyle(name, parent=b["Normal"], **kw)
    return {
        # cover
        "cv_brand": p("cvBrand", fontName="Helvetica",     fontSize=10, textColor=colors.HexColor("#94a3b8")),
        "cv_title": p("cvTitle", fontName="Helvetica-Bold",fontSize=30, leading=36, textColor=colors.white, spaceAfter=8),
        "cv_field": p("cvField", fontName="Helvetica",     fontSize=13, leading=17, textColor=colors.HexColor("#94a3b8")),
        "cv_meta":  p("cvMeta",  fontName="Helvetica",     fontSize=10, leading=14, textColor=colors.HexColor("#cbd5e1")),
        # toc
        "toc_h":    p("tocH",   fontName="Helvetica-Bold", fontSize=18, textColor=C_PRIMARY, spaceAfter=14),
        "toc_1":    p("toc1",   fontName="Helvetica",      fontSize=11, leading=16, textColor=C_MID,   leftIndent=10,  spaceAfter=4),
        "toc_2":    p("toc2",   fontName="Helvetica",      fontSize=9,  leading=13, textColor=C_MUTED, leftIndent=26,  spaceAfter=2),
        # body
        "h1":  p("H1",  fontName="Helvetica-Bold", fontSize=16, leading=20, textColor=colors.white,
                 spaceBefore=0, spaceAfter=0),
        "h2":  p("H2",  fontName="Helvetica-Bold", fontSize=12, leading=15, textColor=C_PRIMARY,
                 spaceBefore=10, spaceAfter=5, keepWithNext=True),
        "h3":  p("H3",  fontName="Helvetica-Bold", fontSize=10.5, leading=13, textColor=C_CYAN,
                 spaceBefore=7, spaceAfter=3, keepWithNext=True),
        "body":p("Body",fontName="Helvetica",       fontSize=9.5, leading=13.5, textColor=C_MID, spaceAfter=5),
        "bull":p("Bull",fontName="Helvetica",       fontSize=9,   leading=12.5, textColor=C_MID,
                 leftIndent=14, firstLineIndent=-10, spaceAfter=2),
        "lbl": p("Lbl", fontName="Helvetica-Bold",  fontSize=9.5, leading=12,  textColor=C_DARK),
        "cap": p("Cap", fontName="Helvetica-Oblique",fontSize=8,  leading=10,  textColor=C_MUTED,
                 spaceAfter=8, alignment=1),
    }


# ── Helpers ───────────────────────────────────────────────────────
def _hr(story):
    story.append(HRFlowable(width="100%", thickness=0.5,
                             color=C_BORDER, spaceAfter=8, spaceBefore=4))

def _banner(story, text, s):
    """Indigo full-width section banner."""
    t = Table([[Paragraph(text, s["h1"])]], colWidths=[W])
    t.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,-1), C_PRIMARY),
        ("TOPPADDING",    (0,0),(-1,-1), 10),
        ("BOTTOMPADDING", (0,0),(-1,-1), 10),
        ("LEFTPADDING",   (0,0),(-1,-1), 14),
        ("RIGHTPADDING",  (0,0),(-1,-1), 14),
    ]))
    story.append(Spacer(1, 8))
    story.append(t)
    story.append(Spacer(1, 10))

def _kv(rows, s):
    """Two-column key→value info table."""
    data = [[Paragraph(k, s["lbl"]), Paragraph(str(v), s["body"])] for k, v in rows]
    t = Table(data, colWidths=[1.7*inch, W - 1.7*inch])
    t.setStyle(TableStyle([
        ("VALIGN",        (0,0),(-1,-1), "TOP"),
        ("TOPPADDING",    (0,0),(-1,-1), 4),
        ("BOTTOMPADDING", (0,0),(-1,-1), 4),
        ("LINEBELOW",     (0,0),(-1,-1), 0.4, C_BORDER),
        ("LEFTPADDING",   (0,0),(-1,-1), 6),
        ("BACKGROUND",    (0,0),(0,-1),  colors.HexColor("#f8fafc")),
    ]))
    return t

def _table(header, rows, s, cw=None):
    """Styled table with indigo header."""
    hrow = [Paragraph(f"<b>{h}</b>", s["cv_meta"]) for h in header]
    drows = [[Paragraph(str(c), s["body"]) for c in r] for r in rows]
    cw = cw or [W / len(header)] * len(header)
    t = Table([hrow] + drows, colWidths=cw, repeatRows=1)
    bg = [colors.white, C_STRIPE]
    t.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,0),  C_PRIMARY),
        ("TEXTCOLOR",     (0,0),(-1,0),  colors.white),
        ("ROWBACKGROUNDS",(0,1),(-1,-1), bg),
        ("GRID",          (0,0),(-1,-1), 0.4, C_BORDER),
        ("VALIGN",        (0,0),(-1,-1), "TOP"),
        ("TOPPADDING",    (0,0),(-1,-1), 5),
        ("BOTTOMPADDING", (0,0),(-1,-1), 5),
        ("LEFTPADDING",   (0,0),(-1,-1), 7),
        ("RIGHTPADDING",  (0,0),(-1,-1), 7),
    ]))
    return t


# ── Charts ────────────────────────────────────────────────────────
def _flowchart(semesters):
    """Semester learning path flowchart."""
    bw, bh, gap = 85, 32, 16
    n = len(semesters)
    total_w = n * (bw + gap) + gap
    d = Drawing(min(total_w, W), 70)
    palette = [C_PRIMARY, C_CYAN, C_VIOLET, C_GREEN, C_AMBER,
               colors.HexColor("#db2777"), colors.HexColor("#ea580c")]
    x = gap
    for i, sem in enumerate(semesters):
        col = palette[i % len(palette)]
        d.add(Rect(x, 18, bw, bh, fillColor=col,
                   strokeColor=colors.white, strokeWidth=0.8, rx=5, ry=5))
        d.add(String(x + bw/2, 38, f"Semester {sem['semester_number']}",
                     fontName="Helvetica-Bold", fontSize=8.5,
                     fillColor=colors.white, textAnchor="middle"))
        d.add(String(x + bw/2, 26, f"{len(sem['courses'])} courses",
                     fontName="Helvetica", fontSize=7,
                     fillColor=colors.HexColor("#e0e7ff"), textAnchor="middle"))
        if i < n - 1:
            ax = x + bw + 2
            ay = 34
            d.add(Line(ax, ay, ax + gap - 4, ay,
                       strokeColor=C_MUTED, strokeWidth=1))
            d.add(Polygon([ax+gap-4, ay, ax+gap-10, ay+4, ax+gap-10, ay-4],
                          fillColor=C_MUTED, strokeColor=C_MUTED))
        x += bw + gap
    return d

def _bar_chart(semesters):
    """Vertical bar chart — credits per semester."""
    n = len(semesters)
    bw = min(48, (W - 50) / max(n, 1))
    totals = [sum(c.get("credits", 3) for c in s["courses"]) for s in semesters]
    max_t = max(totals) if totals else 20
    ch = 90
    total_w = n * (bw + 10) + 50
    d = Drawing(min(total_w, W), ch + 30)
    x = 42
    for i, sem in enumerate(semesters):
        h = int((totals[i] / max_t) * ch)
        col = [C_PRIMARY, C_CYAN, C_VIOLET][i % 3]
        d.add(Rect(x, 20, bw, h, fillColor=col,
                   strokeColor=colors.white, strokeWidth=0.5, rx=3, ry=3))
        d.add(String(x + bw/2, 22 + h, str(totals[i]),
                     fontName="Helvetica-Bold", fontSize=7.5,
                     fillColor=C_DARK, textAnchor="middle"))
        d.add(String(x + bw/2, 8, f"S{sem['semester_number']}",
                     fontName="Helvetica", fontSize=7.5,
                     fillColor=C_MUTED, textAnchor="middle"))
        x += bw + 10
    d.add(String(12, ch/2 + 10, "Credits",
                 fontName="Helvetica-Oblique", fontSize=7,
                 fillColor=C_MUTED, textAnchor="middle"))
    return d

def _skill_bars(skill_levels):
    """Horizontal bar chart for skill mastery."""
    rows = list(skill_levels.items())[:8]
    bar_h, gap_y, lw = 13, 7, 130
    bar_area = W - lw - 50
    height = len(rows) * (bar_h + gap_y) + 20
    d = Drawing(W, height)
    palette = [C_PRIMARY, C_CYAN, C_VIOLET, C_GREEN, C_AMBER,
               colors.HexColor("#db2777"), colors.HexColor("#ea580c"), C_PRIMARY]
    y = height - bar_h - 8
    for i, (skill, level) in enumerate(rows):
        pct = min(max(int(level), 0), 100) / 100
        col = palette[i % len(palette)]
        # track
        d.add(Rect(lw, y, bar_area, bar_h,
                   fillColor=C_BORDER, strokeColor=None))
        # fill
        if pct > 0:
            d.add(Rect(lw, y, bar_area * pct, bar_h,
                       fillColor=col, strokeColor=None, rx=3, ry=3))
        d.add(String(lw - 6, y + 2, skill[:22],
                     fontName="Helvetica", fontSize=7.5,
                     fillColor=C_MID, textAnchor="end"))
        d.add(String(lw + bar_area * pct + 5, y + 2, f"{int(pct*100)}%",
                     fontName="Helvetica-Bold", fontSize=7,
                     fillColor=C_MID, textAnchor="start"))
        y -= (bar_h + gap_y)
    return d


# ── Cover page ────────────────────────────────────────────────────
def _cover(c_canvas, topic, curriculum_data):
    """Draw directly on canvas for a reliable dark cover."""
    c_canvas.saveState()
    # dark background
    c_canvas.setFillColor(C_DARK)
    c_canvas.rect(0, 0, PW, PH, fill=1, stroke=0)
    # top accent stripe
    c_canvas.setFillColor(C_PRIMARY)
    c_canvas.rect(0, PH - 8, PW, 8, fill=1, stroke=0)
    # bottom accent stripe
    c_canvas.rect(0, 0, PW, 5, fill=1, stroke=0)
    # diagonal decorative strip
    c_canvas.setFillColor(colors.HexColor("#1e293b"))
    c_canvas.rect(0, PH * 0.38, PW, PH * 0.62, fill=1, stroke=0)
    # brand label
    c_canvas.setFont("Helvetica", 10)
    c_canvas.setFillColor(colors.HexColor("#94a3b8"))
    c_canvas.drawString(LM, PH - 40, "LERNIX AI  ·  Professional Curriculum Report")
    # topic title
    c_canvas.setFont("Helvetica-Bold", 32)
    c_canvas.setFillColor(colors.white)
    # wrap long titles
    words = topic.split()
    lines, line = [], []
    for w in words:
        line.append(w)
        if c_canvas.stringWidth(" ".join(line), "Helvetica-Bold", 32) > W:
            if len(line) > 1:
                lines.append(" ".join(line[:-1]))
                line = [w]
            else:
                lines.append(" ".join(line))
                line = []
    if line:
        lines.append(" ".join(line))
    y_title = PH - 110
    for ln in lines:
        c_canvas.drawString(LM, y_title, ln)
        y_title -= 42
    # field of study
    c_canvas.setFont("Helvetica", 14)
    c_canvas.setFillColor(colors.HexColor("#94a3b8"))
    c_canvas.drawString(LM, y_title - 10,
                        f"Field of Study:  {curriculum_data.get('field_of_study', '—')}")
    # separator line
    c_canvas.setStrokeColor(C_PRIMARY)
    c_canvas.setLineWidth(1.5)
    c_canvas.line(LM, y_title - 30, LM + W, y_title - 30)
    # meta block
    meta = [
        ("Duration",       f"{curriculum_data.get('duration_semesters','—')} Semesters"),
        ("Total Courses",  str(sum(len(s["courses"]) for s in curriculum_data.get("semesters",[])))),
        ("Generated By",   "LERNIX AI  (IBM Granite)"),
        ("Date",           datetime.now().strftime("%B %d, %Y")),
        ("Paradigm",       "Outcome-Based Education (OBE)"),
        ("Standard",       "ACM / IEEE Joint Guidelines"),
    ]
    y_meta = y_title - 55
    c_canvas.setFont("Helvetica-Bold", 9)
    c_canvas.setFillColor(colors.HexColor("#64748b"))
    for label, val in meta:
        c_canvas.drawString(LM, y_meta, label)
        c_canvas.setFont("Helvetica", 9)
        c_canvas.setFillColor(colors.HexColor("#e2e8f0"))
        c_canvas.drawString(LM + 110, y_meta, val)
        c_canvas.setFont("Helvetica-Bold", 9)
        c_canvas.setFillColor(colors.HexColor("#64748b"))
        y_meta -= 18
    c_canvas.restoreState()


# ── TOC ───────────────────────────────────────────────────────────
def _toc(story, curriculum_data, s):
    story.append(Paragraph("Table of Contents", s["toc_h"]))
    _hr(story)
    entries = [
        ("1", "Program Overview"),
        ("2", "Semester-wise Curriculum"),
    ]
    for sem in curriculum_data.get("semesters", []):
        entries.append(("", f"Semester {sem['semester_number']} — {len(sem['courses'])} Courses"))
    entries += [
        ("3", "Learning Resources"),
        ("4", "Skills Mapping"),
        ("5", "Career Roadmap"),
        ("6", "Capstone Project Recommendations"),
        ("7", "Visual Analytics"),
    ]
    for num, title in entries:
        if num:
            story.append(Paragraph(f"<b>{num}.</b>  {title}", s["toc_1"]))
        else:
            story.append(Paragraph(f"     {title}", s["toc_2"]))
    story.append(PageBreak())


# ── Section 1: Program Overview ───────────────────────────────────
def _overview(story, topic, curriculum_data, report, s):
    _banner(story, "1.  Program Overview", s)
    tc = sum(len(sem["courses"]) for sem in curriculum_data.get("semesters", []))
    cr = sum(c.get("credits", 3)
             for sem in curriculum_data.get("semesters", [])
             for c in sem["courses"])
    story.append(_kv([
        ("Program Title",   topic),
        ("Field of Study",  curriculum_data.get("field_of_study", "—")),
        ("Duration",        f"{curriculum_data.get('duration_semesters','—')} Semesters"),
        ("Total Courses",   str(tc)),
        ("Total Credits",   str(cr)),
        ("Target Audience", report.get("target_audience", "Undergraduate / Professional")),
        ("Design Paradigm", "Outcome-Based Education (OBE)"),
        ("Standard",        "ACM / IEEE Joint Curriculum Guidelines"),
    ], s))
    story.append(Spacer(1, 12))
    story.append(Paragraph("Program Description", s["h2"]))
    story.append(Paragraph(report.get("program_description",
        f"This program provides a structured, industry-aligned pathway through {topic}, "
        f"spanning {curriculum_data.get('duration_semesters','multiple')} semesters of "
        "rigorous academic and practical learning."), s["body"]))
    story.append(Spacer(1, 8))
    story.append(Paragraph("Learning Objectives", s["h2"]))
    for obj in report.get("learning_objectives", [
        f"Master foundational and advanced concepts of {topic}.",
        "Apply industry-standard tools and frameworks in real-world settings.",
        "Design, implement, and evaluate scalable systems.",
        "Collaborate effectively using Agile and DevOps practices.",
        "Demonstrate innovation and research-grade problem solving.",
    ]):
        story.append(Paragraph(f"• {obj}", s["bull"]))
    story.append(PageBreak())


# ── Section 2: Semester-wise Curriculum ──────────────────────────
def _semesters(story, curriculum_data, s):
    _banner(story, "2.  Semester-wise Curriculum", s)
    for sem in curriculum_data.get("semesters", []):
        sn = sem["semester_number"]
        story.append(Paragraph(f"Semester {sn}", s["h2"]))
        # summary table
        story.append(_table(
            ["Code", "Course Title", "Credits", "Difficulty", "Weekly Hrs", "Relevance"],
            [[c.get("code",""), c.get("name",""),
              str(c.get("credits",3)), c.get("difficulty",""),
              f"{c.get('weekly_hours', c.get('credits',3)*2)} hrs",
              f"{c.get('industry_relevance_score',90)}%"]
             for c in sem["courses"]],
            s,
            cw=[0.85*inch, 2.35*inch, 0.65*inch, 1.0*inch, 0.85*inch, 0.8*inch]
        ))
        story.append(Spacer(1, 8))
        for course in sem["courses"]:
            cs = []
            cs.append(Paragraph(
                f"{course.get('code','')}: {course.get('name','')}", s["h3"]))
            cs.append(_kv([
                ("Credits",       str(course.get("credits", 3))),
                ("Difficulty",    course.get("difficulty", "—")),
                ("Weekly Hours",  f"{course.get('weekly_hours', course.get('credits',3)*2)} hrs"),
                ("Relevance",     f"{course.get('industry_relevance_score',90)}%"),
                ("Prerequisites", ", ".join(course.get("prerequisites",[])) or "None"),
            ], s))
            cs.append(Spacer(1, 4))
            cs.append(Paragraph("Detailed Description", s["lbl"]))
            cs.append(Paragraph(course.get("description", "—"), s["body"]))
            cs.append(Paragraph("Learning Outcomes", s["lbl"]))
            for lo in course.get("learning_outcomes", []):
                cs.append(Paragraph(f"• {lo}", s["bull"]))
            if course.get("career_opportunities"):
                cs.append(Paragraph(
                    f"<b>Career Pathways:</b> {', '.join(course['career_opportunities'])}",
                    s["body"]))
            if course.get("recommended_projects"):
                cs.append(Paragraph(
                    f"<b>Recommended Capstone:</b> {', '.join(course['recommended_projects'])}",
                    s["body"]))
            if course.get("assessment_methods"):
                cs.append(Paragraph(
                    f"<b>Assessment Structure:</b> {', '.join(course['assessment_methods'])}",
                    s["body"]))
            cs.append(HRFlowable(width="100%", thickness=0.4, color=C_BORDER,
                                  spaceBefore=5, spaceAfter=5))
            story.append(KeepTogether(cs))
        story.append(PageBreak())


# ── Section 3: Learning Resources ────────────────────────────────
def _resources(story, curriculum_data, report, s):
    _banner(story, "3.  Learning Resources", s)
    res = report.get("learning_resources", {})
    cats = [
        ("Books & Textbooks",        res.get("books", [])),
        ("Official Documentation",   res.get("documentation", [])),
        ("Video Courses & MOOCs",    res.get("video_courses", [])),
        ("Research Papers",          res.get("research_papers", [])),
        ("Industry References",      res.get("industry_references", [])),
    ]
    for title, items in cats:
        if not items:
            continue
        story.append(Paragraph(title, s["h3"]))
        for item in items:
            if isinstance(item, dict):
                parts = [f"<b>{item.get('title','')}</b>"]
                if item.get("author"):
                    parts.append(f"— {item['author']}")
                if item.get("url"):
                    parts.append(f"| {item['url']}")
                story.append(Paragraph("• " + "  ".join(parts), s["bull"]))
            else:
                story.append(Paragraph(f"• {item}", s["bull"]))
        story.append(Spacer(1, 6))
    story.append(Paragraph("Course-level Reference Links", s["h2"]))
    rows = []
    for sem in curriculum_data.get("semesters", []):
        for course in sem["courses"]:
            for r in course.get("resources", []):
                rows.append([course.get("code",""), r.get("title",""), r.get("url","")])
    if rows:
        story.append(_table(
            ["Course Code", "Resource Title", "URL"], rows, s,
            cw=[0.9*inch, 2.4*inch, 3.5*inch]))
    story.append(PageBreak())


# ── Section 4: Skills Mapping ─────────────────────────────────────
def _skills(story, report, s):
    _banner(story, "4.  Skills Mapping", s)
    sm = report.get("skills_mapping", {})
    cats = [
        ("Technical Skills",       sm.get("technical_skills", [])),
        ("Tools & Platforms",      sm.get("tools", [])),
        ("Frameworks & Libraries", sm.get("frameworks", [])),
        ("Industry Competencies",  sm.get("industry_competencies", [])),
    ]
    for cat, items in cats:
        if not items:
            continue
        story.append(Paragraph(cat, s["h3"]))
        cols = min(len(items), 4)
        rows_data = [items[i:i+cols] for i in range(0, len(items), cols)]
        while len(rows_data[-1]) < cols:
            rows_data[-1].append("")
        t = Table(
            [[Paragraph(cell, s["body"]) for cell in row] for row in rows_data],
            colWidths=[W / cols] * cols
        )
        t.setStyle(TableStyle([
            ("BACKGROUND",    (0,0),(-1,-1), colors.HexColor("#eff6ff")),
            ("GRID",          (0,0),(-1,-1), 0.5, C_BORDER),
            ("TOPPADDING",    (0,0),(-1,-1), 5),
            ("BOTTOMPADDING", (0,0),(-1,-1), 5),
            ("LEFTPADDING",   (0,0),(-1,-1), 8),
            ("ALIGN",         (0,0),(-1,-1), "CENTER"),
        ]))
        story.append(t)
        story.append(Spacer(1, 8))
    story.append(Paragraph("Skill Progression Chart", s["h2"]))
    sl = report.get("skill_levels", {})
    if sl:
        story.append(_skill_bars(sl))
        story.append(Paragraph(
            "Figure: Skill mastery levels across the full program.", s["cap"]))
    story.append(PageBreak())


# ── Section 5: Career Roadmap ─────────────────────────────────────
def _career(story, report, s):
    _banner(story, "5.  Career Roadmap", s)
    cr = report.get("career_roadmap", {})
    levels = [
        ("Beginner Roles",      cr.get("beginner_roles", [])),
        ("Intermediate Roles",  cr.get("intermediate_roles", [])),
        ("Advanced Roles",      cr.get("advanced_roles", [])),
    ]
    for title, roles in levels:
        if not roles:
            continue
        story.append(Paragraph(title, s["h3"]))
        rows = []
        for role in roles:
            if isinstance(role, dict):
                rows.append([role.get("title",""), role.get("description",""), role.get("salary","—")])
            else:
                rows.append([str(role), "", "—"])
        story.append(_table(
            ["Role Title", "Description", "Avg. Salary"], rows, s,
            cw=[1.7*inch, 3.5*inch, 1.6*inch]))
        story.append(Spacer(1, 10))
    si = report.get("salary_insights")
    if si:
        story.append(Paragraph("Salary Insights", s["h2"]))
        story.append(_kv(list(si.items()) if isinstance(si, dict) else [(str(si),"")], s))
    story.append(PageBreak())


# ── Section 6: Capstone Recommendations ──────────────────────────
def _capstone(story, report, s):
    _banner(story, "6.  Capstone Project Recommendations", s)
    for i, proj in enumerate(report.get("capstone_projects", []), 1):
        cs = []
        if isinstance(proj, dict):
            cs.append(Paragraph(f"{i}.  {proj.get('title','Project')}", s["h3"]))
            cs.append(Paragraph(proj.get("description",""), s["body"]))
            if proj.get("tech_stack"):
                cs.append(Paragraph(
                    f"<b>Tech Stack:</b>  {', '.join(proj['tech_stack'])}", s["body"]))
            if proj.get("deliverables"):
                cs.append(Paragraph("<b>Deliverables</b>", s["lbl"]))
                for d in proj["deliverables"]:
                    cs.append(Paragraph(f"• {d}", s["bull"]))
            if proj.get("difficulty"):
                cs.append(Paragraph(f"<b>Difficulty Level:</b>  {proj['difficulty']}", s["body"]))
        else:
            cs.append(Paragraph(f"{i}.  {proj}", s["h3"]))
        cs.append(HRFlowable(width="100%", thickness=0.4, color=C_BORDER,
                              spaceBefore=6, spaceAfter=6))
        story.append(KeepTogether(cs))
    story.append(PageBreak())


# ── Section 7: Visual Analytics ───────────────────────────────────
def _visuals(story, curriculum_data, s):
    _banner(story, "7.  Visual Analytics", s)
    sems = curriculum_data.get("semesters", [])
    if not sems:
        story.append(Paragraph("No semester data available.", s["body"]))
        return
    # 7.1 Learning Path Flowchart
    story.append(Paragraph("7.1  Learning Path Flowchart", s["h2"]))
    story.append(Paragraph(
        "Horizontal progression map showing semester sequence and course density.",
        s["body"]))
    story.append(_flowchart(sems))
    story.append(Paragraph(
        "Figure 1: Each block = one semester. Arrows indicate progression direction.",
        s["cap"]))
    story.append(Spacer(1, 18))
    # 7.2 Semester Credit Distribution
    story.append(Paragraph("7.2  Semester Credit Distribution", s["h2"]))
    story.append(Paragraph(
        "Vertical bar chart showing total credit load per semester.", s["body"]))
    story.append(_bar_chart(sems))
    story.append(Paragraph(
        "Figure 2: Credit totals per semester — highlights academic workload spread.",
        s["cap"]))
    story.append(Spacer(1, 18))
    # 7.3 Course Dependency Graph
    story.append(Paragraph("7.3  Course Dependency Graph", s["h2"]))
    story.append(Paragraph(
        "Maps prerequisite relationships between courses across all semesters.",
        s["body"]))
    dep_rows = []
    for sem in sems:
        for course in sem["courses"]:
            dep_rows.append([
                f"S{sem['semester_number']}",
                course.get("code", ""),
                course.get("name", ""),
                ", ".join(course.get("prerequisites", [])) or "None",
            ])
    if dep_rows:
        story.append(_table(
            ["Sem", "Code", "Course Title", "Prerequisites"], dep_rows, s,
            cw=[0.45*inch, 0.9*inch, 2.85*inch, 2.6*inch]))
    story.append(Paragraph(
        "Figure 3: Course prerequisite dependency map.", s["cap"]))


# ── Custom DocTemplate for cover-page canvas drawing ─────────────
class _CoverDoc(BaseDocTemplate):
    def __init__(self, buf, topic, curriculum_data, **kw):
        super().__init__(buf, **kw)
        self._topic = topic
        self._curr = curriculum_data
        frame = Frame(LM, BM, W, PH - TM - BM, id="body")
        self.addPageTemplates([PageTemplate(id="main", frames=[frame])])

    def handle_pageBegin(self):
        super().handle_pageBegin()
        if self.page == 1:
            _cover(self.canv, self._topic, self._curr)


# ── Public API ────────────────────────────────────────────────────
def generate_curriculum_pdf(curriculum_data):
    """Backward-compat wrapper — used by existing export routes."""
    return generate_professional_report(
        topic=curriculum_data.get("export_topic", curriculum_data.get("title", "Curriculum")),
        curriculum_data=curriculum_data,
        report={}
    )


def generate_professional_report(topic, curriculum_data, report):
    """
    University-grade multi-section PDF.
    `report`  dict from llm_service.generate_full_report_data().
    """
    buf = io.BytesIO()
    doc = _CoverDoc(
        buf, topic, curriculum_data,
        pagesize=letter,
        leftMargin=LM, rightMargin=RM,
        topMargin=TM, bottomMargin=BM,
        title=topic,
        author="LERNIX AI",
        subject=f"Curriculum Report — {topic}",
    )
    s = _S()
    story = []
    # page 1 is the canvas-drawn cover; start content from page 2
    story.append(PageBreak())          # triggers cover draw then moves to page 2
    _toc(story, curriculum_data, s)
    _overview(story, topic, curriculum_data, report, s)
    _semesters(story, curriculum_data, s)
    _resources(story, curriculum_data, report, s)
    _skills(story, report, s)
    _career(story, report, s)
    _capstone(story, report, s)
    _visuals(story, curriculum_data, s)
    doc.build(story, canvasmaker=_Canvas)
    buf.seek(0)
    return buf.getvalue()
